// Generated by IcedCoffeeScript 1.6.3-j
(function() {
  var BaseCommand, Config, os, path;

  Config = require('./config').Config;

  os = require('os');

  path = require('path');

  exports.BaseCommand = BaseCommand = (function() {
    function BaseCommand(argv) {
      this.config = new Config(argv);
    }

    BaseCommand.prototype.run = function(cb) {
      return cb(new Error("unimplemented"));
    };

    return BaseCommand;

  })();

}).call(this);
