// Generated by IcedCoffeeScript 1.6.3-j
(function() {
  var Config;

  exports.Config = Config = (function() {
    function Config(argv) {
      this.argv = argv;
    }

    return Config;

  })();

}).call(this);
