// Generated by IcedCoffeeScript 1.6.3-j
(function() {
  var Config, constants, url_join,
    __slice = [].slice;

  constants = require('./constants').constants;

  url_join = function() {
    var arg, args, parts, _i, _len, _ref;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    parts = [args[0]];
    _ref = args.slice(1);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      arg = _ref[_i];
      if (parts.slice(-1)[0].slice(-1)[0] !== '/') {
        parts.push('/');
      }
      parts.push(arg);
    }
    return parts.join('');
  };

  exports.Config = Config = (function() {
    function Config(argv) {
      this.argv = argv;
    }

    Config.prototype.url_prefix = function() {
      return this.argv("u", "url-prefix") || contants.url_prefix;
    };

    Config.prototype.make_url = function(u) {
      return url_join(this.url_prefix(), u);
    };

    return Config;

  })();

}).call(this);
