// Generated by IcedCoffeeScript 1.7.0-a
(function() {
  exports.constants = {
    url_prefix: {
      https: "https://dist.keybase.io/",
      http: "http://dist.keybase.io/"
    },
    canonical_host: "keybase.io",
    index_timeout: 60 * 60 * 24 * 100,
    links: {
      stable: 'stable',
      current: 'current'
    },
    uid_email: {
      code: "code@keybase.io",
      index: "index@keybase.io"
    }
  };

}).call(this);
