// Generated by IcedCoffeeScript 1.6.3-j
(function() {
  exports.constants = {
    url_prefix: "https://dist.keybase.io/",
    canonical_host: "keybase.io",
    index_timeout: 60 * 60 * 24 * 100,
    uid_email: {
      code: "code@keybase.io",
      index: "index@keybase.io"
    }
  };

}).call(this);
