// Generated by IcedCoffeeScript 1.6.3-j
(function() {
  var BaseCommand, BufferOutStream, GPG, GetIndex, Installer, KeySetup, KeyUpgrade, SoftwareUpgrade, chain, constants, fullname, iced, keyring, log, make_esc, request, __iced_k, __iced_k_noop, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  iced = require('iced-coffee-script/lib/coffee-script/iced').runtime;
  __iced_k = __iced_k_noop = function() {};

  BaseCommand = require('./base').BaseCommand;

  _ref = require('gpg-wrapper'), keyring = _ref.keyring, BufferOutStream = _ref.BufferOutStream, GPG = _ref.GPG;

  make_esc = require('iced-error').make_esc;

  request = require('./request');

  fullname = require('./package').fullname;

  constants = require('./constants').constants;

  KeySetup = require('./key_setup').KeySetup;

  KeyUpgrade = require('./key_upgrade').KeyUpgrade;

  GetIndex = require('./get_index').GetIndex;

  SoftwareUpgrade = require('./software_upgrade').SoftwareUpgrade;

  log = require('./log');

  chain = require('iced-utils').util.chain;

  exports.Installer = Installer = (function(_super) {
    __extends(Installer, _super);

    function Installer(argv) {
      Installer.__super__.constructor.call(this, argv);
    }

    Installer.prototype.cleanup = function(cb) {
      var e2, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase-node-installer/src/installer.iced",
            funcname: "Installer.cleanup"
          });
          _this.config.cleanup(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return e2 = arguments[0];
              };
            })(),
            lineno: 24
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          if (typeof e2 !== "undefined" && e2 !== null) {
            log.error("In cleanup: " + e2);
          }
          if ((typeof err === "undefined" || err === null) && (_this["package"] != null)) {
            log.info("Succesful install: " + (_this["package"].filename()));
          }
          return cb();
        };
      })(this));
    };

    Installer.prototype.run = function(cb) {
      var esc, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      log.debug("+ Installer::run");
      cb = chain(cb, this.cleanup.bind(this));
      esc = make_esc(cb, "Installer::_run2");
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase-node-installer/src/installer.iced",
            funcname: "Installer.run"
          });
          _this.config.make_tmpdir(esc(__iced_deferrals.defer({
            lineno: 36
          })));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "/Users/max/src/keybase-node-installer/src/installer.iced",
              funcname: "Installer.run"
            });
            _this.setup_keyring(esc(__iced_deferrals.defer({
              lineno: 37
            })));
            __iced_deferrals._fulfill();
          })(function() {
            (function(__iced_k) {
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "/Users/max/src/keybase-node-installer/src/installer.iced",
                funcname: "Installer.run"
              });
              _this.key_setup(esc(__iced_deferrals.defer({
                lineno: 38
              })));
              __iced_deferrals._fulfill();
            })(function() {
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "/Users/max/src/keybase-node-installer/src/installer.iced",
                  funcname: "Installer.run"
                });
                _this.get_index(esc(__iced_deferrals.defer({
                  lineno: 39
                })));
                __iced_deferrals._fulfill();
              })(function() {
                (function(__iced_k) {
                  __iced_deferrals = new iced.Deferrals(__iced_k, {
                    parent: ___iced_passed_deferral,
                    filename: "/Users/max/src/keybase-node-installer/src/installer.iced",
                    funcname: "Installer.run"
                  });
                  _this.key_upgrade(esc(__iced_deferrals.defer({
                    lineno: 40
                  })));
                  __iced_deferrals._fulfill();
                })(function() {
                  (function(__iced_k) {
                    __iced_deferrals = new iced.Deferrals(__iced_k, {
                      parent: ___iced_passed_deferral,
                      filename: "/Users/max/src/keybase-node-installer/src/installer.iced",
                      funcname: "Installer.run"
                    });
                    _this.software_upgrade(esc(__iced_deferrals.defer({
                      lineno: 41
                    })));
                    __iced_deferrals._fulfill();
                  })(function() {
                    log.debug("- Installer::run");
                    return cb(null);
                  });
                });
              });
            });
          });
        };
      })(this));
    };

    Installer.prototype.key_setup = function(cb) {
      return (new KeySetup(this.config)).run(cb);
    };

    Installer.prototype.get_index = function(cb) {
      return (new GetIndex(this.config)).run(cb);
    };

    Installer.prototype.key_upgrade = function(cb) {
      return (new KeyUpgrade(this.config)).run(cb);
    };

    Installer.prototype.software_upgrade = function(cb) {
      return (new SoftwareUpgrade(this.config)).run(cb);
    };

    Installer.prototype.setup_keyring = function(cb) {
      keyring.init({
        log: log,
        get_tmp_keyring_dir: (function(_this) {
          return function() {
            return _this.config.get_tmpdir();
          };
        })(this)
      });
      this.config.set_master_ring();
      return cb(null);
    };

    return Installer;

  })(BaseCommand);

}).call(this);
