// Generated by IcedCoffeeScript 1.7.1-a
(function() {
  var KeyInstall, KeySetup, a_json_parse, athrow, constants, fpeq, iced, key_query, keyring, keyset, log, make_esc, __iced_k, __iced_k_noop, _ref;

  iced = require('iced-coffee-script/lib/coffee-script/iced').runtime;
  __iced_k = __iced_k_noop = function() {};

  keyring = require('gpg-wrapper').keyring;

  constants = require('./constants').constants;

  log = require('./log');

  make_esc = require('iced-error').make_esc;

  keyset = require('../json/keyset');

  fpeq = require('pgp-utils').util.fpeq;

  _ref = require('iced-utils').util, athrow = _ref.athrow, a_json_parse = _ref.a_json_parse;

  KeyInstall = require('./key_install').KeyInstall;

  key_query = require('./util').key_query;

  exports.KeySetup = KeySetup = (function() {
    function KeySetup(config) {
      this.config = config;
      this._key = null;
    }

    KeySetup.prototype.key = function() {
      return this._key;
    };

    KeySetup.prototype.check_prepackaged_key = function(cb) {
      var a, b, body, err, esc, json, res, v, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      esc = make_esc(cb, "KeySetup::check_prepackaged_key");
      v = keyset.version;
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase-node-installer/src/key_setup.iced",
            funcname: "KeySetup.check_prepackaged_key"
          });
          _this.config.request("/sig/files/" + v + "/keyset.json", esc(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                res = arguments[0];
                return body = arguments[1];
              };
            })(),
            lineno: 27
          })));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "/Users/max/src/keybase-node-installer/src/key_setup.iced",
              funcname: "KeySetup.check_prepackaged_key"
            });
            a_json_parse(body, esc(__iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  return json = arguments[0];
                };
              })(),
              lineno: 28
            })));
            __iced_deferrals._fulfill();
          })(function() {
            var _ref1;
            err = (a = typeof json !== "undefined" && json !== null ? json.version : void 0) !== v ? new Error("Version mismatch; expected " + v + " but got " + a) : (a = typeof json !== "undefined" && json !== null ? (_ref1 = json.keys.code) != null ? _ref1.fingerprint : void 0 : void 0) == null ? (console.log(json), new Error("Fingerprint failure; none found in server version")) : !(fpeq(a, (b = keyset.keys.code.fingerprint))) ? new Error("Fingerprint mismatch; expected " + a + " but got " + b) : null;
            return cb(err);
          });
        };
      })(this));
    };

    KeySetup.prototype.install_prepackaged_key = function(cb) {
      var err, ki, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      log.debug("+ Installing prepackaged key: v" + keyset.version);
      ki = new KeyInstall(this.config, keyset);
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase-node-installer/src/key_setup.iced",
            funcname: "KeySetup.install_prepackaged_key"
          });
          ki.run(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return err = arguments[0];
              };
            })(),
            lineno: 46
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          log.debug("- Installed: -> " + err);
          return cb(err);
        };
      })(this));
    };

    KeySetup.prototype.run = function(cb) {
      var esc, index_key, version, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      esc = make_esc(cb, "SetupKeyRunner::run");
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase-node-installer/src/key_setup.iced",
            funcname: "KeySetup.run"
          });
          _this.find_latest_key('index', esc(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return index_key = arguments[0];
              };
            })(),
            lineno: 54
          })));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "/Users/max/src/keybase-node-installer/src/key_setup.iced",
              funcname: "KeySetup.run"
            });
            _this.find_latest_key('code', esc(__iced_deferrals.defer({
              assign_fn: (function(__slot_1) {
                return function() {
                  __slot_1._key = arguments[0];
                  return version = arguments[1];
                };
              })(_this),
              lineno: 55
            })));
            __iced_deferrals._fulfill();
          })(function() {
            (function(__iced_k) {
              if ((typeof index_key !== "undefined" && index_key !== null) && (_this._key != null)) {
                return __iced_k(_this.config.set_key_version(version));
              } else {
                (function(__iced_k) {
                  __iced_deferrals = new iced.Deferrals(__iced_k, {
                    parent: ___iced_passed_deferral,
                    filename: "/Users/max/src/keybase-node-installer/src/key_setup.iced",
                    funcname: "KeySetup.run"
                  });
                  _this.check_prepackaged_key(esc(__iced_deferrals.defer({
                    lineno: 59
                  })));
                  __iced_deferrals._fulfill();
                })(function() {
                  (function(__iced_k) {
                    __iced_deferrals = new iced.Deferrals(__iced_k, {
                      parent: ___iced_passed_deferral,
                      filename: "/Users/max/src/keybase-node-installer/src/key_setup.iced",
                      funcname: "KeySetup.run"
                    });
                    _this.install_prepackaged_key(esc(__iced_deferrals.defer({
                      lineno: 60
                    })));
                    __iced_deferrals._fulfill();
                  })(function() {
                    return __iced_k(_this.config.set_key_version(keyset.version));
                  });
                });
              }
            })(function() {
              return cb(null);
            });
          });
        };
      })(this));
    };

    KeySetup.prototype.find_latest_key = function(which, cb) {
      var c, comments, em, err, esc, key, m, master, max, out, query, uid, uids, versions, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      esc = make_esc(cb, "SetupKeyRunner::find_latest_key");
      em = constants.uid_email[which];
      err = key = null;
      master = this.config.master_ring();
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase-node-installer/src/key_setup.iced",
            funcname: "KeySetup.find_latest_key"
          });
          master.read_uids_from_key({}, esc(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return uids = arguments[0];
              };
            })(),
            lineno: 71
          })));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          comments = (function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = uids.length; _i < _len; _i++) {
              uid = uids[_i];
              if ((uid != null) && (uid.email === em)) {
                _results.push(uid.comment);
              }
            }
            return _results;
          })();
          versions = (function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = comments.length; _i < _len; _i++) {
              c = comments[_i];
              if ((m = c.match(/^v(\d+)$/))) {
                _results.push(parseInt(m[1]));
              }
            }
            return _results;
          })();
          (function(__iced_k) {
            if (versions.length === 0) {
              return __iced_k(log.warn("No " + which + "-signing key (" + em + ") in primary GPG keychain"));
            } else {
              max = Math.max.apply(Math, versions);
              query = key_query(max, which);
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "/Users/max/src/keybase-node-installer/src/key_setup.iced",
                  funcname: "KeySetup.find_latest_key"
                });
                master.find_keys({
                  query: query
                }, esc(__iced_deferrals.defer({
                  assign_fn: (function() {
                    return function() {
                      return out = arguments[0];
                    };
                  })(),
                  lineno: 79
                })));
                __iced_deferrals._fulfill();
              })(function() {
                (function(__iced_k) {
                  if (out.length === 0) {
                    return __iced_k(err = new Error("Didn't find any key for query " + query));
                  } else {
                    (function(__iced_k) {
                      if (out.length > 1) {
                        return __iced_k(err = new Error("Found too many keys that matched " + query));
                      } else {
                        key = master.make_key({
                          key_id_64: out[0],
                          username: em
                        });
                        (function(__iced_k) {
                          __iced_deferrals = new iced.Deferrals(__iced_k, {
                            parent: ___iced_passed_deferral,
                            filename: "/Users/max/src/keybase-node-installer/src/key_setup.iced",
                            funcname: "KeySetup.find_latest_key"
                          });
                          key.load(__iced_deferrals.defer({
                            assign_fn: (function() {
                              return function() {
                                return err = arguments[0];
                              };
                            })(),
                            lineno: 84
                          }));
                          __iced_deferrals._fulfill();
                        })(function() {
                          return __iced_k(err ? key = null : void 0);
                        });
                      }
                    })(__iced_k);
                  }
                })(__iced_k);
              });
            }
          })(function() {
            return cb(err, key, max);
          });
        };
      })(this));
    };

    return KeySetup;

  })();

}).call(this);
