// Generated by IcedCoffeeScript 1.6.3-j
(function() {
  var KeyUpgrade, fpeq, hash_json, keyring, make_esc;

  make_esc = require('iced-error').make_esc;

  keyring = require('gpg-wrapper').keyring;

  fpeq = require('pgp-utils').util.fpeq;

  hash_json = require('./util').hash_json;

  exports.KeyUpgrade = KeyUpgrade = (function() {
    function KeyUpgrade(config) {
      this.config = config;
    }

    KeyUpgrade.prototype.run = function(cb) {
      return cb(null);
    };

    return KeyUpgrade;

  })();

}).call(this);
