// Generated by IcedCoffeeScript 1.6.3-j
(function() {
  var BaseCommand, HelpCommand, Main, VersionCommand, find_bin, getopt, gpg, iced, make_esc, package_json, run, __iced_k, __iced_k_noop,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  iced = require('iced-coffee-script/lib/coffee-script/iced').runtime;
  __iced_k = __iced_k_noop = function() {};

  getopt = require('./getopt').getopt;

  package_json = require('../package.json');

  make_esc = require('iced-error').make_esc;

  gpg = require('gpg-wrapper');

  find_bin = function() {
    var k, v, _ref;
    _ref = package_json.bin;
    for (k in _ref) {
      v = _ref[k];
      return k;
    }
  };

  exports.BaseCommand = BaseCommand = (function() {
    function BaseCommand(argv) {
      this.argv = argv;
    }

    return BaseCommand;

  })();

  VersionCommand = (function(_super) {
    __extends(VersionCommand, _super);

    function VersionCommand() {
      return VersionCommand.__super__.constructor.apply(this, arguments);
    }

    VersionCommand.prototype.run = function(cb) {
      console.log("" + (find_bin()) + " v" + package_json.version);
      return cb(null);
    };

    return VersionCommand;

  })(BaseCommand);

  HelpCommand = (function(_super) {
    __extends(HelpCommand, _super);

    function HelpCommand() {
      return HelpCommand.__super__.constructor.apply(this, arguments);
    }

    HelpCommand.prototype.run = function(cb) {
      console.log("usage: " + (find_bin()) + " [<keybase-version>]\n\n\tUpgrade or install a version of keybase.  Check signatures for Keybase.io's signing\n\tkey. You can provide a specific version or by default you'll get the most recent\n\tversion.\n\n\tVersion: " + package_json.version);
      return cb(null);
    };

    return HelpCommand;

  })(BaseCommand);

  Main = (function() {
    Main.OPTS = {
      a: {
        alias: 'about',
        action: "storeTrue",
        help: 'display version and command name, then quit'
      }
    };

    function Main() {
      this.cmd = null;
    }

    Main.prototype.parse_args = function(cb) {
      var err;
      err = null;
      this.argv = getopt(process.argv.slice(2), {
        flags: ["h", "v", "help", "version", "?"]
      });
      if (this.argv.get("v", "version")) {
        this.cmd = new VersionCommand();
      } else if (this.argv.get("h", "?", "help")) {
        this.cmd = new HelpCommand();
      } else {
        err = new Error("unimplemented!");
      }
      return cb(err);
    };

    Main.prototype.run = function(cb) {
      var esc, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      esc = make_esc(cb, "run");
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/home/max/src/keybase-node-installer/src/main.iced",
            funcname: "Main.run"
          });
          _this.setup(esc(__iced_deferrals.defer({
            lineno: 73
          })));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "/home/max/src/keybase-node-installer/src/main.iced",
              funcname: "Main.run"
            });
            _this.cmd.run(esc(__iced_deferrals.defer({
              lineno: 74
            })));
            __iced_deferrals._fulfill();
          })(function() {
            return cb(null);
          });
        };
      })(this));
    };

    Main.prototype.main = function() {
      var err, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/home/max/src/keybase-node-installer/src/main.iced",
            funcname: "Main.main"
          });
          _this.run(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return err = arguments[0];
              };
            })(),
            lineno: 80
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          if (typeof err !== "undefined" && err !== null) {
            console.warn(err.message);
          }
          return process.exit(typeof err !== "undefined" && err !== null ? -2 : 0);
        };
      })(this));
    };

    Main.prototype.setup = function(cb) {
      var esc, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      esc = make_esc(cb, "setup");
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/home/max/src/keybase-node-installer/src/main.iced",
            funcname: "Main.setup"
          });
          _this.parse_args(esc(__iced_deferrals.defer({
            lineno: 88
          })));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          return cb(null);
        };
      })(this));
    };

    return Main;

  })();

  exports.run = run = function() {
    return (new Main).main();
  };

}).call(this);
