// Generated by IcedCoffeeScript 1.6.3-j
(function() {
  var BaseCommand, HelpCommand, Installer, KeyJsonCommand, Main, VersionCommand, bin, constants, fullname, getopt, gpg, iced, json_stringify_sorted, key, make_esc, run, version, __iced_k, __iced_k_noop, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  iced = require('iced-coffee-script/lib/coffee-script/iced').runtime;
  __iced_k = __iced_k_noop = function() {};

  getopt = require('./getopt').getopt;

  _ref = require('./package'), fullname = _ref.fullname, bin = _ref.bin, version = _ref.version;

  make_esc = require('iced-error').make_esc;

  BaseCommand = require('./base').BaseCommand;

  Installer = require('./installer').Installer;

  gpg = require('gpg-wrapper');

  constants = require('./constants').constants;

  key = require('./key');

  json_stringify_sorted = require('iced-utils').util.json_stringify_sorted;

  VersionCommand = (function(_super) {
    __extends(VersionCommand, _super);

    function VersionCommand() {
      return VersionCommand.__super__.constructor.apply(this, arguments);
    }

    VersionCommand.prototype.run = function(cb) {
      console.log(fullname());
      return cb(null);
    };

    return VersionCommand;

  })(BaseCommand);

  HelpCommand = (function(_super) {
    __extends(HelpCommand, _super);

    function HelpCommand(argv, err) {
      this.err = err != null ? err : null;
      HelpCommand.__super__.constructor.call(this, argv);
    }

    HelpCommand.prototype.run = function(cb) {
      console.log("usage: " + (bin()) + " [-vh?] [-C] [-u <url-prefix>] [<keybase-version>]\n\n\tUpgrade or install a version of keybase.  Check signatures for Keybase.io's signing\n\tkey. You can provide a specific version or by default you'll get the most recent\n\tversion.\n\nBoolean Flags:\n\t-v/--version       -- Print the version and quit\n\t-h/--help          -- Print the help message and quit\n\t-C/--skip-cleanup  -- Don't delete temporary files after install\n\nOptions:\n\t-u/--url-prefix    -- Specify a URL prefix for fetching (default: " + constants.url_prefix + ")\n\nVersion: " + (version()) + "\n");
      return cb(this.err);
    };

    return HelpCommand;

  })(BaseCommand);

  KeyJsonCommand = (function(_super) {
    __extends(KeyJsonCommand, _super);

    function KeyJsonCommand() {
      return KeyJsonCommand.__super__.constructor.apply(this, arguments);
    }

    KeyJsonCommand.prototype.run = function(cb) {
      console.log(json_stringify_sorted(key));
      return cb(null);
    };

    return KeyJsonCommand;

  })(BaseCommand);

  Main = (function() {
    Main.OPTS = {
      a: {
        alias: 'about',
        action: "storeTrue",
        help: 'display version and command name, then quit'
      }
    };

    function Main() {
      this.cmd = null;
    }

    Main.prototype.parse_args = function(cb) {
      var err, flags;
      err = null;
      flags = ["h", "v", "k", "key-json", "help", "version", "?", "skip-cleanup", "C"];
      this.argv = getopt(process.argv.slice(2), {
        flags: flags
      });
      if (this.argv.get("v", "version")) {
        this.cmd = new VersionCommand();
      } else if (this.argv.get("h", "?", "help")) {
        this.cmd = new HelpCommand();
      } else if (this.argv.get().length > 1) {
        this.cmd = new HelpCommand(this.argv, new Error("Usage error: only zero or one argument allowed"));
      } else if (this.argv.get("k", "key-json")) {
        this.cmd = new KeyJsonCommand();
      } else {
        this.cmd = new Installer(this.argv);
      }
      return cb(err);
    };

    Main.prototype.run = function(cb) {
      var esc, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      esc = make_esc(cb, "run");
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase-node-installer/src/main.iced",
            funcname: "Main.run"
          });
          _this.setup(esc(__iced_deferrals.defer({
            lineno: 101
          })));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "/Users/max/src/keybase-node-installer/src/main.iced",
              funcname: "Main.run"
            });
            _this.cmd.run(esc(__iced_deferrals.defer({
              lineno: 102
            })));
            __iced_deferrals._fulfill();
          })(function() {
            return cb(null);
          });
        };
      })(this));
    };

    Main.prototype.main = function() {
      var err, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase-node-installer/src/main.iced",
            funcname: "Main.main"
          });
          _this.run(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return err = arguments[0];
              };
            })(),
            lineno: 108
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          if (typeof err !== "undefined" && err !== null) {
            console.warn(err.message);
          }
          return process.exit(typeof err !== "undefined" && err !== null ? -2 : 0);
        };
      })(this));
    };

    Main.prototype.setup = function(cb) {
      var esc, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      esc = make_esc(cb, "setup");
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase-node-installer/src/main.iced",
            funcname: "Main.setup"
          });
          _this.parse_args(esc(__iced_deferrals.defer({
            lineno: 116
          })));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          return cb(null);
        };
      })(this));
    };

    return Main;

  })();

  exports.run = run = function() {
    return (new Main).main();
  };

}).call(this);
