// Generated by IcedCoffeeScript 1.7.1-a
(function() {
  var Engine, check_cmd, exec, iced, npm, __iced_k, __iced_k_noop, _config;

  iced = require('iced-coffee-script/lib/coffee-script/iced').runtime;
  __iced_k = __iced_k_noop = function() {};

  Engine = require('gpg-wrapper').Engine;

  exec = require('child_process').exec;

  _config = null;

  exports.set_config = function(c) {
    return _config = c;
  };

  exports.check = check_cmd = function(cb) {
    var cmd, err, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    cmd = _config.get_cmd('npm');
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/Users/max/src/keybase-node-installer/src/npm.iced"
        });
        exec("" + cmd + " version", __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return err = arguments[0];
            };
          })(),
          lineno: 13
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        return cb(err);
      };
    })(this));
  };

  exports.npm = npm = function(_arg, cb) {
    var args, eng, err, rc, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    args = _arg.args;
    eng = new Engine({
      args: args
    });
    eng.name = _config.get_cmd('npm');
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/Users/max/src/keybase-node-installer/src/npm.iced"
        });
        eng.run().wait(__iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return rc = arguments[0];
            };
          })(),
          lineno: 21
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        if (rc !== 0) {
          err = new Error("npm exit code " + rc);
          err.rc = rc;
        }
        return cb(err);
      };
    })(this));
  };

}).call(this);
