// Generated by IcedCoffeeScript 1.6.3-j
(function() {
  var Engine, iced, npm, __iced_k, __iced_k_noop;

  iced = require('iced-coffee-script/lib/coffee-script/iced').runtime;
  __iced_k = __iced_k_noop = function() {};

  Engine = require('gpg-wrapper').Engine;

  exports.npm = npm = function(_arg, cb) {
    var args, eng, err, rc, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    args = _arg.args;
    eng = new Engine({
      args: args
    });
    eng.name = "npm";
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/Users/max/src/keybase-node-installer/src/npm.iced"
        });
        eng.run().wait(__iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return rc = arguments[0];
            };
          })(),
          lineno: 8
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        if (rc !== 0) {
          err = new Error("npm exit code " + rc);
          err.rc = rc;
        }
        return cb(err);
      };
    })(this));
  };

}).call(this);
