// Generated by IcedCoffeeScript 1.6.3-j
(function() {
  var constants, createHash, json_stringify_sorted;

  json_stringify_sorted = require('iced-utils').util.json_stringify_sorted;

  createHash = require('crypto').createHash;

  constants = require('./constants').constants;

  exports.hash_json = function(x) {
    return createHash('SHA512').update(json_stringify_sorted(x)).digest('hex');
  };

  exports.key_query = function(v, which) {
    return "(v" + v + ") <" + which + "@" + constants.canonical_host + ">";
  };

}).call(this);
